---
name: Pull Request

permissions:
  id-token: write
  contents: read

on:
  - pull_request

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - run: npm install

      - uses: pulumi/auth-actions@v1
        with:
          organization: andreswebs
          requested-token-type: urn:pulumi:token-type:access_token:personal

      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: dev
